import 'package:telegram/modules/user_model.dart';

List<UserModel> users = [
  UserModel(name: "Mohamed", message: "How are you ?", time: "11:45 PM"),
  UserModel(name: "3bdullah", message: "Hi, 3bdullah", time: "02:50 PM"),
  UserModel(name: "Ali", message: "Let's go", time: "11:42 PM"),
  UserModel(name: "Ahmed", message: "Why ?!", time: "01:45 PM"),
  UserModel(name: "Nasser", message: "How are you ?", time: "11:22 PM"),
  UserModel(name: "Essam", message: "No", time: "01:10 PM"),
  UserModel(name: "Mohamed", message: "Thanks", time: "07:45 PM"),
  UserModel(name: "Mohamed", message: "How are you ?", time: "11:45 PM"),
  UserModel(name: "3bdullah", message: "Hi, 3bdullah", time: "02:50 PM"),
  UserModel(name: "Ali", message: "Let's go", time: "11:42 PM"),
  UserModel(name: "Ahmed", message: "Why ?!", time: "01:45 PM"),
  UserModel(name: "Nasser", message: "How are you ?", time: "11:22 PM"),
  UserModel(name: "Essam", message: "No", time: "01:10 PM"),
  UserModel(name: "Mohamed", message: "Thanks", time: "07:45 PM"),
  UserModel(name: "Mohamed", message: "How are you ?", time: "11:45 PM"),
  UserModel(name: "3bdullah", message: "Hi, 3bdullah", time: "02:50 PM"),
  UserModel(name: "Ali", message: "Let's go", time: "11:42 PM"),
  UserModel(name: "Ahmed", message: "Why ?!", time: "01:45 PM"),
  UserModel(name: "Nasser", message: "How are you ?", time: "11:22 PM"),
  UserModel(name: "Essam", message: "No", time: "01:10 PM"),
  UserModel(name: "Mohamed", message: "Thanks", time: "07:45 PM"),
  UserModel(name: "Mohamed", message: "How are you ?", time: "11:45 PM"),
  UserModel(name: "3bdullah", message: "Hi, 3bdullah", time: "02:50 PM"),
  UserModel(name: "Ali", message: "Let's go", time: "11:42 PM"),
  UserModel(name: "Ahmed", message: "Why ?!", time: "01:45 PM"),
  UserModel(name: "Nasser", message: "How are you ?", time: "11:22 PM"),
  UserModel(name: "Essam", message: "No", time: "01:10 PM"),
  UserModel(name: "Mohamed", message: "Thanks", time: "07:45 PM"),
];
